### ISSUE TITLE
An unexpected error for video streaming with recording 

### ISSUE THREAD

**Issue by jensen0915** [yutasuzuki/react-native-record-screen#59]
Package version: 'com.github.HBiSoft:HBRecorder:0.1.13'
iOS platform is no problem 
but Android platform has faced a crush with Android 8, but the error will be disappeared above Android 8 (e.g., test ok on 10).

The error log shows as follows, please give some advice. Thanks in advance.

2022-02-17 11:13:32.190 21089-21320/com.rebleeding_monitoring_app **W/IMediaDeathNotifier: media server died**
2022-02-17 11:13:32.191 21089-21089/com.rebleeding_monitoring_app I/System.out: HBRecorderOnComplete
2022-02-17 11:13:32.191 21089-21320/com.rebleeding_monitoring_app **E/MediaPlayerNative: error (100, 0)**
2022-02-17 11:13:32.192 21089-21089/com.rebleeding_monitoring_app D/AndroidRuntime: Shutting down VM
2022-02-17 11:13:32.197 21089-21089/com.rebleeding_monitoring_app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.rebleeding_monitoring_app, PID: 21089
    kotlin.KotlinNullPointerException
        at com.reactnativerecordscreen.RecordScreenModule.HBRecorderOnComplete(RecordScreenModule.kt:143)
        at com.hbisoft.hbrecorder.HBRecorder.callback(HBRecorder.java:340)
        at com.hbisoft.hbrecorder.FileObserver$1.run(FileObserver.java:73)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:251)
        at android.app.ActivityThread.main(ActivityThread.java:6572)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by HBiSoft** [comment]
I would suggest updating you `HBRecorder` version. A lot has changed since `0.1.13`.

**Comment by yutasuzuki** [comment]
@HBiSoft 
Sorry for the delay in thanking you.
Thank you for your support.
And thank you for the great library.
